title: "Symbiosis AGI | Docs"
description: "Documentation for SymAGI"

remote_theme: just-the-docs/just-the-docs 

url: "https://docs.symagi.com"
permalink: pretty

favicon_ico: "/favicon.ico"

search_enabled: true

aux_links:
  "SymAGI":
    - "https://symagi.com"

color_scheme: dark
